/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh_chats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/media-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_media_policy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["set_media_policy"];
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/media/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["backfill_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_message"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/messages/{message_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["message_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/messages/{message_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["message_media"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/senders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_senders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sync_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chat_id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["track_chat"];
        post?: never;
        delete: operations["untrack_chat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/downloads/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["media_progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_media"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{media_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{media_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["media_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{media_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retry_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/senders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_senders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/senders/{sender_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sender"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sync_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sync_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sync_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["json_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["yaml_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttachmentDto: {
            file_name?: string | null;
            kind: components["schemas"]["AttachmentKindDto"];
            mime_type?: string | null;
            /** Format: int64 */
            size?: number | null;
            telegram_file_id?: string | null;
        };
        /** @enum {string} */
        AttachmentKindDto: "photo" | "video" | "audio" | "voice" | "document" | "sticker" | "animation" | "other";
        ChatDto: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["ChatKindDto"];
            stats?: null | components["schemas"]["ChatStatsDto"];
            title?: string | null;
            /** @description Whether the chat is opted in for collection. */
            tracked: boolean;
            username?: string | null;
        };
        /** @enum {string} */
        ChatKindDto: "private" | "group" | "supergroup" | "channel";
        /**
         * @description Sort order of `GET /chats`.
         * @enum {string}
         */
        ChatSortDto: "title" | "last_message" | "message_count";
        ChatStatsDto: {
            /** Format: int64 */
            deleted_count: number;
            /**
             * Format: date-time
             * @description Timestamps of the oldest / newest non-deleted message.
             */
            first_message_at?: string | null;
            /** @description Whether history backfill reached the start of the chat. */
            history_complete: boolean;
            /** @description Sanitized reason of the last failed sync, cleared by the next successful checkpoint. */
            last_error?: string | null;
            /** Format: date-time */
            last_message_at?: string | null;
            /** Format: date-time */
            last_sync_completed_at?: string | null;
            /**
             * Format: int64
             * @description Non-deleted archived messages.
             */
            message_count: number;
        };
        ComponentStatusDto: {
            detail?: string | null;
            state: string;
        };
        ErrorDetail: {
            code: string;
            message: string;
            request_id: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        ForwardDto: {
            /**
             * Format: date-time
             * @description When the original message was sent.
             */
            date?: string | null;
            /**
             * Format: int64
             * @description Original author or channel (marked ID) when Telegram exposes it.
             */
            from_id?: number | null;
            /** @description Name of the original author (also set for users who hide their account). */
            from_name?: string | null;
        };
        HealthDto: {
            status: string;
        };
        MediaDownloadDto: {
            /** Format: int64 */
            byte_size?: number | null;
            content_url?: string | null;
            /** Format: int32 */
            height?: number | null;
            /** Format: int64 */
            id: number;
            last_error?: string | null;
            /** Format: int64 */
            next_attempt_at?: number | null;
            /** Format: int64 */
            ordinal: number;
            state: string;
            variant: string;
            /** Format: int32 */
            width?: number | null;
        };
        MediaPolicyDto: {
            auto_archive: boolean;
        };
        /** @description Cumulative current image downloads, grouped by chat and variant. Retrying is a subset of failed. */
        MediaProgressDto: {
            /** Format: int64 */
            chat_id: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            interrupted: number;
            /** Format: int64 */
            queued: number;
            /** Format: int64 */
            retrying: number;
            /** Format: int64 */
            running: number;
            /** Format: int64 */
            succeeded: number;
            /** Format: int64 */
            superseded: number;
            title?: string | null;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            unavailable: number;
            variant: string;
        };
        /** @description Messages around an anchor, both lists oldest first. */
        MessageContextDto: {
            after: components["schemas"]["MessageDto"][];
            /** @description Pass as `after` to `GET .../messages` to keep scrolling to newer messages. */
            after_cursor?: string | null;
            anchor: components["schemas"]["MessageDto"];
            before: components["schemas"]["MessageDto"][];
            /** @description Pass as `before` to `GET .../messages` to keep scrolling to older messages. */
            before_cursor?: string | null;
            has_more_after: boolean;
            has_more_before: boolean;
        };
        MessageDto: {
            attachments: components["schemas"]["AttachmentDto"][];
            /** Format: int64 */
            chat_id: number;
            /** Format: date-time */
            collected_at: string;
            /**
             * Format: date-time
             * @description Set when the message was deleted on Telegram (only returned with `include_deleted=true`).
             */
            deleted_at?: string | null;
            /** Format: date-time */
            edited_at?: string | null;
            forward?: null | components["schemas"]["ForwardDto"];
            /** Format: int64 */
            id: number;
            is_deleted: boolean;
            /** @description Channel post signature (`post_author`); not the sender. */
            post_author?: string | null;
            /** Format: int64 */
            reply_to?: number | null;
            sender?: null | components["schemas"]["SenderDto"];
            /** Format: int64 */
            sender_id?: number | null;
            /**
             * @description Search results only: excerpt (about 120 characters) around the first match, `null` when
             *     no match position could be determined. `text` always carries the full message.
             */
            snippet?: string | null;
            text?: string | null;
            /** Format: date-time */
            timestamp: string;
        };
        MessagePageDto: {
            has_more: boolean;
            items: components["schemas"]["MessageDto"][];
            /** @description Opaque cursor; pass it back as `before` to get the next page. */
            next_cursor?: string | null;
        };
        RateLimitDto: {
            /**
             * Format: int64
             * @description Configured base interval (`SYNC_PAGE_DELAY_MS`).
             */
            base_interval_ms: number;
            /**
             * Format: int64
             * @description Current minimum interval between history requests (grows after FLOOD_WAIT).
             */
            interval_ms: number;
            /** Format: date-time */
            last_flood_at?: string | null;
            /** Format: int64 */
            last_flood_wait_secs?: number | null;
        };
        SearchIndexDto: {
            /**
             * Format: int64
             * @description Messages in the index.
             */
            indexed: number;
            /**
             * @description `ready`; `rebuilding` or `stale` (search then uses a slower substring scan until
             *     `tgarchive search rebuild-index` / `db init` completes).
             */
            state: string;
            /**
             * Format: int64
             * @description Messages with text that belong in the index.
             */
            total: number;
            /**
             * Format: int32
             * @description Index format version stored in the database (0 = never built).
             */
            version: number;
        };
        /**
         * @description Result order of `GET /messages/search`.
         * @enum {string}
         */
        SearchSortDto: "relevance" | "time";
        SenderChatDto: {
            /** Format: int64 */
            chat_id: number;
            kind: components["schemas"]["ChatKindDto"];
            /** Format: date-time */
            last_message_at?: string | null;
            /** Format: int64 */
            message_count: number;
            title?: string | null;
        };
        /** @description A sender plus its per-chat breakdown (most messages first). */
        SenderDetailDto: {
            /** Format: int64 */
            chat_count: number;
            chats: components["schemas"]["SenderChatDto"][];
            display_name?: string | null;
            /** Format: date-time */
            first_message_at?: string | null;
            /** Format: int64 */
            id: number;
            is_bot?: boolean | null;
            is_self: boolean;
            kind: components["schemas"]["SenderKindDto"];
            /** Format: date-time */
            last_message_at?: string | null;
            /** Format: int64 */
            message_count: number;
            /** @description Observed names, newest observation first. */
            name_history: components["schemas"]["SenderNameHistoryDto"][];
            username?: string | null;
        };
        SenderDto: {
            /** @description Profile name; for a chat/channel posting as itself, the chat title. */
            display_name?: string | null;
            /** Format: int64 */
            id: number;
            /** @description Telegram's bot flag; null = unknown or not a user. */
            is_bot?: boolean | null;
            /** @description True when the sender is the bound Telegram account. */
            is_self: boolean;
            username?: string | null;
        };
        /** @enum {string} */
        SenderKindDto: "user" | "chat" | "channel" | "unknown";
        /** @description A historical display name / username combination. */
        SenderNameDto: {
            display_name?: string | null;
            username?: string | null;
        };
        /**
         * @description Names tgarchive observed for a sender. Timestamps are when tgarchive saw the names, not when
         *     the user changed them.
         */
        SenderNameHistoryDto: {
            display_name?: string | null;
            /** Format: date-time */
            first_seen_at: string;
            /** Format: date-time */
            last_seen_at: string;
            username?: string | null;
        };
        SenderPageDto: {
            items: components["schemas"]["SenderProfileDto"][];
            /** @description Opaque cursor; pass it back as `cursor` to get the next page. */
            next_cursor?: string | null;
        };
        /** @description A sender with archive-wide aggregates. */
        SenderProfileDto: {
            /**
             * Format: int64
             * @description Chats in which the sender has messages.
             */
            chat_count: number;
            /** @description Profile name; for a channel posting as itself, the channel title. */
            display_name?: string | null;
            /** Format: date-time */
            first_message_at?: string | null;
            /** Format: int64 */
            id: number;
            /** @description Telegram's bot flag; null = unknown or not a user. */
            is_bot?: boolean | null;
            /** @description The Telegram account this archive is bound to. */
            is_self: boolean;
            kind: components["schemas"]["SenderKindDto"];
            /** Format: date-time */
            last_message_at?: string | null;
            /** @description True when a text query matched only a historical name (see `matched_name`). */
            matched_history: boolean;
            matched_name?: null | components["schemas"]["SenderNameDto"];
            /**
             * Format: int64
             * @description Messages by this sender (deleted ones only with `include_deleted=true`).
             */
            message_count: number;
            username?: string | null;
        };
        /**
         * @description Sort order of `GET /senders`.
         * @enum {string}
         */
        SenderSortDto: "messages" | "last_message" | "name";
        SenderSummaryDto: {
            display_name?: string | null;
            /** Format: int64 */
            id: number;
            is_bot?: boolean | null;
            /**
             * Format: int64
             * @description Non-deleted messages by this sender in the chat.
             */
            message_count: number;
            username?: string | null;
        };
        StatusDto: {
            collector: components["schemas"]["ComponentStatusDto"];
            rate_limit?: null | components["schemas"]["RateLimitDto"];
            /** @description Full-text search index state. */
            search_index: components["schemas"]["SearchIndexDto"];
            sync_jobs: components["schemas"]["SyncJobDto"][];
            /**
             * Format: int64
             * @description Deletions that could not be attributed to a chat (kept as tombstones).
             */
            unresolved_deletions: number;
        };
        SyncJobChatDto: {
            /** Format: int64 */
            chat_id: number;
            /** Format: int64 */
            committed_count: number;
            error_summary?: string | null;
            state: string;
            title?: string | null;
        };
        SyncJobDto: {
            /** @description Per-chat progress; only present on `GET /sync/jobs/{id}`. */
            chats?: components["schemas"]["SyncJobChatDto"][] | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Sanitized single-line failure reason (at most 300 chars; never message text). */
            error_summary?: string | null;
            has_error: boolean;
            id: string;
            /**
             * Format: int64
             * @description Seconds Telegram asked to wait, for `rate_limited` jobs.
             */
            retry_after_secs?: number | null;
            scope: string;
            /** Format: date-time */
            started_at?: string | null;
            state: string;
        };
        /** @description Response of `PUT /chats/{id}/tracking`: the chat, plus backfill info when requested. */
        TrackChatDto: components["schemas"]["ChatDto"] & {
            /** @description `queued` for a newly enqueued job, `already_running` when an existing job was reused. */
            backfill?: string | null;
            /** @description History sync job covering this chat (only with `backfill=true`). */
            backfill_job_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chats: {
        parameters: {
            query?: {
                /** @description Only return tracked (collected) chats. */
                tracked?: boolean;
                /** @description Sort order; default is by chat ID. */
                sort?: components["schemas"]["ChatSortDto"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDto"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refresh_chats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDto"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Marked Telegram chat ID */
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_media_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPolicyDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    set_media_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaPolicyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPolicyDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    backfill_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDownloadDto"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_chat_messages: {
        parameters: {
            query?: {
                chat_id?: number;
                sender_id?: number;
                /** @description Exact channel post signature. */
                post_author?: string;
                from?: string;
                to?: string;
                before?: string;
                after?: string;
                limit?: number;
                /** @description Also return deleted messages (flagged with `is_deleted`/`deleted_at`). */
                include_deleted?: boolean;
                /** @description Hide messages from known bots (`senders.is_bot=1`); unknown senders are kept. */
                exclude_bots?: boolean;
            };
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePageDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_message: {
        parameters: {
            query?: {
                /** @description Also return the message if it was deleted. */
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                chat_id: number;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    message_context: {
        parameters: {
            query?: {
                /** @description Messages older than the anchor (0-100, default 20). */
                before?: number;
                /** @description Messages newer than the anchor (0-100, default 20). */
                after?: number;
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                chat_id: number;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageContextDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Anchor message not found (or deleted without include_deleted) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    message_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDownloadDto"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_chat_senders: {
        parameters: {
            query?: {
                /** @description Maximum senders returned (1-1000, default 100). */
                limit?: number;
            };
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Senders with non-deleted messages in the chat, most messages first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SenderSummaryDto"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sync_chat: {
        parameters: {
            query?: {
                /**
                 * @description Re-download the whole history and backfill NULL sender/post-author/forward/attachment
                 *     metadata of archived messages (text, versions and deletions are untouched). Resumable.
                 */
                refetch?: boolean;
            };
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Chat is not tracked (code chat_not_tracked) or a conflicting job is active (code conflict) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    track_chat: {
        parameters: {
            query?: {
                /** @description Also enqueue a history sync for the chat (needs the running collector). Reuses an active job instead of duplicating it. */
                backfill?: boolean;
            };
            header?: never;
            path: {
                /** @description Marked Telegram chat ID */
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat is now tracked (idempotent); with backfill=true also carries the history sync job id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackChatDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Storage unavailable, or backfill requested without a running collector / with a full queue */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    untrack_chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Marked Telegram chat ID */
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat is no longer tracked; stored messages are kept (idempotent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    media_progress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaProgressDto"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDownloadDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    archive_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDownloadDto"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDownloadDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    media_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified local image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    retry_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDownloadDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_messages: {
        parameters: {
            query?: {
                chat_id?: number;
                sender_id?: number;
                /** @description Exact channel post signature. */
                post_author?: string;
                from?: string;
                to?: string;
                before?: string;
                after?: string;
                limit?: number;
                /** @description Also return deleted messages (flagged with `is_deleted`/`deleted_at`). */
                include_deleted?: boolean;
                /** @description Hide messages from known bots (`senders.is_bot=1`); unknown senders are kept. */
                exclude_bots?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePageDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    search_messages: {
        parameters: {
            query: {
                q: string;
                chat_id?: number;
                sender_id?: number;
                /** @description Exact channel post signature. */
                post_author?: string;
                from?: string;
                to?: string;
                /** @description Cursor from the previous page's `next_cursor`. */
                before?: string;
                /** @description Only with `sort=time`: cursor for the newer direction. */
                after?: string;
                limit?: number;
                /** @description Also return deleted messages (flagged with `is_deleted`/`deleted_at`). */
                include_deleted?: boolean;
                /** @description Hide messages from known bots (`senders.is_bot=1`); unknown senders are kept. */
                exclude_bots?: boolean;
                /** @description Result order; default `relevance`. */
                sort?: components["schemas"]["SearchSortDto"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePageDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_senders: {
        parameters: {
            query?: {
                /**
                 * @description Substring of display name or username (NFKC + case-insensitive, Chinese substrings work),
                 *     `@username` (exact) or a numeric sender ID.
                 */
                q?: string;
                /** @description Order; default `messages`. */
                sort?: components["schemas"]["SenderSortDto"];
                /** @description Page size (1-1000, default 100). */
                limit?: number;
                /** @description Cursor from the previous page's `next_cursor`. */
                cursor?: string;
                /** @description Count deleted messages too. */
                include_deleted?: boolean;
                /** @description `true` = only bots, `false` = only non-bots (unknown included); omitted = everyone. */
                is_bot?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Senders with message counts, chat counts and activity range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SenderPageDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_sender: {
        parameters: {
            query?: {
                /** @description Count deleted messages too. */
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                /** @description Marked sender ID */
                sender_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sender with per-chat breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SenderDetailDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sync_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_sync_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job with per-chat progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sync_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    json_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI JSON document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    yaml_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI YAML document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": unknown;
                };
            };
        };
    };
}
