//! Embedded single-page web UI (`web/dist`, generated by `build.rs`).
use axum::{
    body::Body,
    extract::Request,
    http::{HeaderValue, Method, StatusCode, header},
    response::{IntoResponse, Response},
};

use super::{ApiError, RequestId};

include!(concat!(env!("OUT_DIR"), "/web_assets.rs"));

const CSP: &str = "default-src 'self'; img-src 'self' data:; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'";
const IMMUTABLE: &str = "public, max-age=31536000, immutable";

pub(super) fn asset(path: &str) -> Option<&'static [u8]> {
    ASSETS
        .iter()
        .find(|(name, _)| *name == path)
        .map(|(_, bytes)| *bytes)
}

fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next().unwrap_or("") {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn is_backend_path(path: &str) -> bool {
    ["/api", "/health", "/openapi"].iter().any(|prefix| {
        path.strip_prefix(prefix)
            .is_some_and(|rest| rest.is_empty() || rest.starts_with(['/', '.']))
    })
}

/// Router fallback: UI files and SPA routes for GET/HEAD; JSON 404 for everything else.
pub(super) async fn fallback(request: Request) -> Response {
    let path = request.uri().path();
    let method_ok = matches!(*request.method(), Method::GET | Method::HEAD);
    if !method_ok || is_backend_path(path) {
        let id = request
            .extensions()
            .get::<RequestId>()
            .map_or_else(|| "unknown".to_owned(), |id| id.0.clone());
        return ApiError::not_found(id).into_response();
    }
    let name = path.trim_start_matches('/');
    let (body, name, cache) = match asset(name).filter(|_| !name.is_empty()) {
        Some(bytes) => (
            bytes,
            name,
            if name.starts_with("assets/") {
                IMMUTABLE
            } else {
                "no-cache"
            },
        ),
        // Missing file requests (something.ext) are real 404s; extensionless paths are client routes.
        None if name.starts_with("assets/")
            || name.rsplit('/').next().is_some_and(|f| f.contains('.')) =>
        {
            return (StatusCode::NOT_FOUND, "not found").into_response();
        }
        None => match asset("index.html") {
            Some(bytes) => (bytes, "index.html", "no-cache"),
            None => return (StatusCode::NOT_FOUND, "web UI is not built").into_response(),
        },
    };
    let mut response = Response::new(if *request.method() == Method::HEAD {
        Body::empty()
    } else {
        Body::from(body)
    });
    let headers = response.headers_mut();
    headers.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static(content_type(name)),
    );
    headers.insert(header::CACHE_CONTROL, HeaderValue::from_static(cache));
    headers.insert(header::CONTENT_LENGTH, HeaderValue::from(body.len()));
    headers.insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    headers.insert(
        header::REFERRER_POLICY,
        HeaderValue::from_static("no-referrer"),
    );
    headers.insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(CSP),
    );
    response
}
